### ISSUE TITLE
Template/parcellation info popups often hinder minimizing the sidebar 

### ISSUE THREAD

**Issue by dickscheid** [HumanBrainProject/interactive-viewer#514]
Assume the sidebar is open (template/parcellation selector, possibly search list / connectivity browser), and the user is currently using it so the mouse pointer is on top of the sidebar - maybe just on the parcellation selector. Then, if the user wants to minimize the sidebar, the mouse pointer will very likely come across the (i) info icon of the parcellation or template, since they are close to the minimization button (the leftwards arrow). 

When hovering the info icons, a popup info window for the template or parcellation will appear for some seconds, which hides the minimization button, make it impossible for the user to click it. The user then has to wait until the hover disappears automatically, or know that when clicking on the background window, the info window will disappear. Both cases however are inconvenient for the user. 

Suggestions to improve: 

1. Position the info (i) icons of template and parcellation somewhere else so it is less likely to hover them.

or, from my perspective much preferred!

2. Require click on the (i) icon before the info windows pop up , so hover will not have any effect.

And, suggested in both cases 

3. Allow to dismiss the info window also by clicking anywhere on it (except links/buttons included in it).

**Comment by xgui3783** [comment]
issue will no longer be relevant after v2.3.0 UI changes

**Comment by xgui3783** [comment]
obsolete by v2.3.0
