### ISSUE TITLE
Disable region name display on hover when region menu is activated

### ISSUE THREAD

**Issue by dickscheid** [HumanBrainProject/interactive-viewer#536]
When the region menu is active, it would be reasonable not to display the region name of the same region in addition on hover, see screenshot. 

<img width="536" alt="grafik" src="https://user-images.githubusercontent.com/1436846/83963350-aa646d80-a8a5-11ea-9045-a5516113765f.png">

Possibly this becomes obsolete with the planned next generation region menu located in the side-panel, but if it is a quick fix it woudl be good to resolve.

**Comment by xgui3783** [comment]
no longer applies via v2.3.0 ui change

**Comment by xgui3783** [comment]
obsolete by v2.3.0
