### ISSUE TITLE
[bug] After second change of template coordinate transformation back-end does not work

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#647]
steps to reproduce:

0/ go to /, select human multilevel, select mni152 template space
1/ change position of template on the viewer 
2/ change template to Colin 27 (after changing template position should be the same)
3/ change template again to mni152

expected behavior:
The position should be the same

actual behavior:
The position is restored to the center

**Comment by xgui3783** [comment]
fixed by #677
