### ISSUE TITLE
[bug] It is possible to select multiple regions from the viewer

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#686]
Version: v2.2.3
c770b553304bd201a57c4f35f8cfbddbda5d7ced

steps to reproduce:

0/ go to /, select human multilevel, select mni152 template space
1/ Navigate and click on position: [-0.256mm, 6.976mm, 57.959mm]

expected behavior:
One region should be selected

actual behavior:
Two regions are selected

**Comment by xgui3783** [comment]
This is a known bug, and can't be prevented in any meaningful way
unfortunately.

**Comment by xgui3783** [comment]
This issue will actually come up again when we have multiple layers of interactability. landmark, parcellation region, etc. We should come up with a priority, and a strategy to resolve in the case of a tie in priority (issue being described)

**Comment by xgui3783** [comment]
also, can you quote hash and/or version? I will make a github issue template soon so that we keep track of these.

**Comment by fsdavid** [comment]
I think we can fix it by adding a small context menu with 2 options. Look at the screenshot: 
![image](https://user-images.githubusercontent.com/26521731/97024513-2f9ba680-1557-11eb-99fd-e4e6011c7fba.png)

**Comment by xgui3783** [comment]
No, we just got rid of region context menu, and I do not really want to bring it back (yet)

**Comment by xgui3783** [comment]
bandaid fix: only selects the first region
