### ISSUE TITLE
[Bug] Connectivity coloring appears when closing selected region when 2 region is selected

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#687]
steps to reproduce:

0/ go to /, select human multilevel, select mni152 template space
1/ select region "Area 6ma (preSMA, mesial SFG) - left hemisphere" and "Area 6ma (preSMA, mesial SFG) - right hemisphere" together from the viewer
2/ expand and collapse Connectivity
3/ deselect region

expected behavior:
Map coloring should restore

actual behavior:
Map applies connectivity coloring

**Comment by xgui3783** [comment]
cannot reproduce. I got the expected beahviour

**Comment by fsdavid** [comment]
Sorry step 1 was wrong 2 region should be selected, so "Ch 123 (Basal Forebrain) - left hemisphere" and "Ch 123 (Basal Forebrain) - right hemisphere" toegether

**Comment by xgui3783** [comment]
still cannot reproduce.

Connectivity data never showed for me.

**Comment by fsdavid** [comment]
![image](https://user-images.githubusercontent.com/26521731/97151400-c0e56580-176f-11eb-98b8-647d0579f5b3.gif)

**Comment by fsdavid** [comment]
Could you please look at the gif?
![Oct-26-2020 09-45-31](https://user-images.githubusercontent.com/26521731/97151603-03a73d80-1770-11eb-9217-a9f1ded18c8c.gif)

**Comment by xgui3783** [comment]
that is not CH 123

**Comment by fsdavid** [comment]
Yeah, Ch 123 has not connectivity for this version of the connectivity dataset and it was not possible to explore bug at this region (my mistake sorry)

**Comment by xgui3783** [comment]
bandaid fix maybe fixing #686 , but should debug thoroughly

**Comment by xgui3783** [comment]
bandaided by #691 

@fsdavid do you want to keep this issue open so you can fix it later?

**Comment by fsdavid** [comment]
I think for now, it is better to close. We can reopen if the problem appears in the future.
