### ISSUE TITLE
Improve random color generation for parcellations without explicit color assignment

### ISSUE THREAD

**Issue by ch-schiffer** [HumanBrainProject/interactive-viewer#750]
A random color is generated for brain areas if they have no explicit color assignment using the "rgb" attribute. Currently, this color generation is based only on labelIndex, which is very often identical, resulting in the same color. It would be better to include other attributes in the random color generation (for example ngId) to make sure a wider range of colors gets generated.

**Comment by xgui3783** [comment]
fixed by #856
