### ISSUE TITLE
[BUG] Getting error while fetching connectivity data

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#757]
steps to reproduce:
Load Human brain Atlas 

expected behavior:
The console should not log any errors

actual behavior:
The console logs error:

`Unhandled Promise rejection: Unexpected token < in JSON at position 0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Unexpected token < in JSON at position 0 SyntaxError: Unexpected token < in JSON at position 0`

**Comment by xgui3783** [comment]
I see.. this should be logged with connectivity browser, not iav imo.

**Comment by fsdavid** [comment]
> I see.. this should be logged with connectivity browser, not iav imo.
> 
> Edit: was the http request made by iav or Conn browser?

You are right, error is caused on the connectivity browser side
