### ISSUE TITLE
[Bug] After change connectivity source, if new source does not have data it breaks

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#758]
Steps to reproduce:

1. Load Cytoarchitectonic maps - v1.18
2. Select region "Area STS2 (STS) - right hemisphere"
3. Expand the connectivity
4. change connectivity from "1000BRAINS study" to "Averaged_FC_JuBrain_184Regions"

Expected Behavior
Instead of a connectivity diagram, it should return a message that connectivity is not available for the current region

actual Bihevior 
It keeps "1000BRAINS study" diagram on the screen

**Comment by xgui3783** [comment]
perhaps related, as of 6181c38da7065d21d8c5fc1ea8bcafe0d3628667, on init, iav tries to fetch `https://connectivity-query-v1-1-connectivity.apps-dev.hbp.eu/v1.1/studies/1345998a08539dc24bda8817c7d5804558d83b1c`, but returns 500

**Comment by fsdavid** [comment]
The rison is a different one. Fixed in d070569f0c15e431153095519845f7cc11efed4f

**Comment by xgui3783** [comment]
fixed by #776
