### ISSUE TITLE
[Bug] Unpin dataset does not work on datasets modal view

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#762]
steps to reproduce:

1. Go to: https://interactive-viewer-next.apps-dev.hbp.eu/
2. Select "Multilevel Human Atlas"
3. Pin any dataset
4. open pinned datasets
5. Click on the dataset name
6. Dataset modal should be appear

expected behavior:
Modal should contain button "Unpin dataset"

actual behavior:
Modal has the button "Pin dataset" even if the dataset is already pinned and it does not work.

**Comment by xgui3783** [comment]
fixed by #769
