### ISSUE TITLE
[Bug] Sidebar area view does not look pretty for some screen sizes

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#799]
Steps to reproduce:
1. Go to: http://localhost:8080/?templateSelected=MNI+152+ICBM+2009c+Nonlinear+Asymmetric&parcellationSelected=Cytoarchitectonic+maps+-+v1.18&cRegionsSelected=%7B%22jubrain+mni152+v18+right%22%3A%224G%22%7D&cNavigation=0.0.0.-W000..2_HXp6.-M9Nw.2__9Ne.zrs8h..BSR0..2rrfW%7E.Mubm%7E.TiEf%7E..2FCl

Expected Behaviour:
![image](https://user-images.githubusercontent.com/26521731/101507260-aad5e200-3976-11eb-9d1b-cf950728288d.png)

Actual Behaviour
![image](https://user-images.githubusercontent.com/26521731/101506980-5599d080-3976-11eb-9f73-42bd5de3c230.png)

**Comment by xgui3783** [comment]
fixed by #803, albeit awkward fix for now (see screenshot)

![Screenshot from 2020-12-10 10-30-57](https://user-images.githubusercontent.com/19381783/101756214-15516400-3ad6-11eb-9bbe-16a375bdf1f5.png)

at least it is not **as** ugly
