### ISSUE TITLE
[Bug] Go back from viewer to splash screen after region was selected

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#800]
Steps tp reproduce:

1. Go to: https://interactive-viewer-next.apps-dev.hbp.eu/
2. Select any template 
3. Select any region
4. Click the browsers back buttons until going back to the splash screen

Actual behavior
![image](https://user-images.githubusercontent.com/26521731/101507941-672fa800-3977-11eb-90c5-f29afdaac103.png)

**Comment by xgui3783** [comment]
fixed by #803 . add to e2e test
