### ISSUE TITLE
[Bug] Connectivity dataset preview should contain "explore" button if dataset exists in KG 

### ISSUE THREAD

**Issue by fsdavid** [HumanBrainProject/interactive-viewer#853]
to reproduce:

1/ go to human multilevel
2/ Select any region
3/ open connectivity
4/ change connectivity source to Averaged_FC_JuBrain_246Regions_HCP_REST_FIX_AVER_MEAN

Expected behaviour:
Connectivity dataset preview should contain "explore" button if dataset exists in KG

Actual behaviour:
Connectivity dataset preview does not have an "explore" button

**Comment by fsdavid** [comment]
to reproduce:

1/ go to human multilevel
2/ Select any region
3/ open connectivity
4/ change connectivity source to `Averaged_FC_JuBrain_246Regions_HCP_REST_FIX_AVER_MEAN`

Expected behaviour:
Connectivity dataset preview should contain "explore" button if dataset exists in KG

Actual behaviour:
Connectivity dataset preview does not have an "explore" button

**Comment by xgui3783** [comment]
fixed by #854
